PrivateKey = "1dWugnvjDswaHMLMQ3aRHZC6EtV8XmMK"
HTTPAddress = "http://grandmaison-one-pre.hrgame.com.cn/gm"
ServerListInfo = {Url="http://grandmaison-one-pre.hrgame.com.cn/front/query_servers", PostData={Channel=0,DisgardNotOpened=false,Env="prerelease",ClientVersion="0.0.1",NeedGame=true}}
Commands = "../../BinGame/commands.md"
GroupServerList = [
    {Group=204,Name="公会"},
    {Group=201,Name="好友"},
    {Group=202,Name="秘境"},
    {Group=16,Name="聊天"},
    {Group=13,Name="mail"},
    {Group=50,Name="front"},
    {Group=2,Name="login"},
    ]